language: node_js
node_js:
  - "7"

cache:
  yarn: true
  directories:
    - node_modules

env:
  global:
    - secure: "W1+I2TDqoF6fosZQ1c4uOyfCTBGSbsAsQXVy4AxazC31Ldd8udG2yk8vlmDEGsR/ZIw0rb4Mu6Plrnb/lpFdbHzihMEXpPIIcohj6ol06Bqoxtu1UO1gBFc2ad9VbZ6NNVyNoosSNyYY9a/luQmO7ov+mdJfFu+Iizr6awHC/WsPO+ityFk4y/TwnNQw74Z3mQGBSH2PGed4LsrMJZDKL4HMsiSm/L394h2Y+WoFnXLe7eeCyXITS69Na+InVJZmJ+S7yeMXCsL+UtdIHKk6efS26XK05eiJ//AdRnNbVEC4D0BdmDKzLp3MGI4v8FJWy3BSLs8OI6YHer0Z05geA4qV2JVurvjlYMYEeXPgnVMmsMpOAu83yCANqYy7i8IyutUTpmWqH77Pai7HP3IcX5Xxc1K4YaaU6AyZOAam/bqpO3a86O7KHDadtshkaG95WdLAom7RtGBT26BYNLQy40hCk90PyGXCXfjzFmDzXXnIzGoZbsHSQDyAV0pxwrcdBVHEyZaw+J/8sjjhJ98hj0ZQzT7u0jLgh2YXWQAE4b7+8uWiKVpbIfK1/K7wae2NwntqSPM/AIMavthNygKDA4U/9QM8ZwWD3es+vlGtDVj7AFaSJh41S2mStirKp6v8apigFZUebldjOYB56s2MRiJiZaf5x4gWBPfpdA50+Ak="

branches:
  only:
    - master

notifications:
  email: false

before_install:
  - openssl aes-256-cbc -K $encrypted_bd2fe598737f_key -iv $encrypted_bd2fe598737f_iv -in travis-release-key.enc -out release_key -d

script:
  # - npm run build

after_success:
  # only run for master branch, we don't want to release PRs and other branches
  # - 'if [ "$TRAVIS_PULL_REQUEST" != "true" ] && [ "$TRAVIS_BRANCH" == "master" ]; then bash ./travis_release.sh; fi'
